symbols_embedding_dim: 384
in_fft_n_layers: 6
in_fft_n_heads: 1
in_fft_d_head: 64
in_fft_conv1d_kernel_size: 3
in_fft_conv1d_filter_size: 384
in_fft_output_size: 384
p_in_fft_dropout: 0.1
p_in_fft_dropatt:  0.1
p_in_fft_dropemb: 0
out_fft_n_layers: 6
out_fft_n_heads: 1
out_fft_d_head: 64
out_fft_conv1d_kernel_size: 3
out_fft_conv1d_filter_size: 384
out_fft_output_size: 384
p_out_fft_dropout: 0.1
p_out_fft_dropatt: 0.1
p_out_fft_dropemb: 0.0
speaker_emb_weight: 1
mask_type: 'square'
local_window_size: 20
